version: '3.8'

networks:
    monorepo:
        driver: bridge

services:
    one-frontend-nginx:
        build:
            context: ${RELATIVE_PATH_TO_ROOT}
            dockerfile: ${ONE_PATH_DOCKER}/frontend-nginx/Dockerfile
            args:
                SHARED_CONFIG_PATH: ${SHARED_CONFIG_PATH}
                APP_PATH: ${ONE_PATH}/frontend
                CONF_PATH: ${ONE_PATH_DOCKER}/frontend-nginx
        privileged: true
        restart: unless-stopped
        ports:
            - "1104:443"
        volumes:
            - ${RELATIVE_PATH_TO_ROOT}:/var/www/app/
            - ./${ONE_PATH}/frontend-nginx/log/:/var/log/nginx/
            - ${RELATIVE_PATH_TO_ROOT}${SHARED_CONFIG_PATH}/ssl/:/etc/nginx/ssl/
        networks:
            - monorepo

    one-backend-php:
        build:
            context: ${RELATIVE_PATH_TO_ROOT}
            dockerfile: ${ONE_PATH_DOCKER}/backend-php/Dockerfile
            args:
                SHARED_CONFIG_PATH: ${SHARED_CONFIG_PATH}
                APP_PATH: ${ONE_PATH}/backend
                CONF_PATH: ${ONE_PATH_DOCKER}/backend-php
        privileged: true
        restart: unless-stopped
        volumes:
            - ${RELATIVE_PATH_TO_ROOT}:/var/www/app/
        networks:
            - monorepo
    one-backend-nginx:
        build:
            context: ${RELATIVE_PATH_TO_ROOT}
            dockerfile: ${ONE_PATH_DOCKER}/backend-nginx/Dockerfile
            args:
                SHARED_CONFIG_PATH: ${SHARED_CONFIG_PATH}
                APP_PATH: ${ONE_PATH}/backend
                CONF_PATH: ${ONE_PATH_DOCKER}/backend-nginx
        privileged: true
        restart: unless-stopped
        ports:
            - "1103:443"
        volumes:
            - ${RELATIVE_PATH_TO_ROOT}${ONE_PATH}/backend/public/:/var/www/app/${ONE_PATH}/backend/public/
            - ./${ONE_PATH}/backend-nginx/log/:/var/log/nginx/
            - ${RELATIVE_PATH_TO_ROOT}${SHARED_CONFIG_PATH}/ssl/:/etc/nginx/ssl/
        networks:
            - monorepo
    one-backend-mysql:
        build:
            context: ${RELATIVE_PATH_TO_ROOT}
            dockerfile: ${ONE_PATH_DOCKER}/backend-mysql/Dockerfile
            args:
                SHARED_CONFIG_PATH: ${SHARED_CONFIG_PATH}
        privileged: true
        restart: unless-stopped
        environment:
            - MYSQL_ROOT_PASSWORD=root
        env_file:
            - ${RELATIVE_PATH_TO_ROOT}${ONE_PATH}/backend/.env
        ports:
            - "1101:3306"
        volumes:
            - ./${ONE_PATH}/backend-mysql/data/:/var/lib/mysql/
        networks:
            - monorepo

    one-library-onelone:
        build:
            context: ${RELATIVE_PATH_TO_ROOT}
            dockerfile: ${ONE_PATH_DOCKER}/library-onelone/Dockerfile
            args:
                SHARED_CONFIG_PATH: ${SHARED_CONFIG_PATH}
                APP_PATH: ${ONE_PATH}/library/onelone
        privileged: true
        restart: unless-stopped
        volumes:
            - ${RELATIVE_PATH_TO_ROOT}:/var/www/app/
        networks:
            - monorepo
    one-library-oneltwo:
        build:
            context: ${RELATIVE_PATH_TO_ROOT}
            dockerfile: ${ONE_PATH_DOCKER}/library-oneltwo/Dockerfile
            args:
                SHARED_CONFIG_PATH: ${SHARED_CONFIG_PATH}
                APP_PATH: ${ONE_PATH}/library/oneltwo
        privileged: true
        restart: unless-stopped
        volumes:
            - ${RELATIVE_PATH_TO_ROOT}:/var/www/app/
        networks:
            - monorepo
